version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=turk"
      - "POSTGRES_PASSWORD=turk"

  redis:
    image: redis
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      args:
        RAILS_ENV: development


    volumes:
      - ./:/rails_app
    ports:
      - "3000:80"
    environment:
      - "RAILS_ENV=development"
      - "REDIS_URL=redis://redis:6379"
      - "DATABASE_URL=postgresql://turk:turk@postgres/caesar_development"
      - "DATABASE_URL_TEST=postgresql://turk:turk@postgres/caesar_test"
    links:
      - redis:redis
      - postgres:postgres
