# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15a16af136a3a3893f42787c2e90bec67634b4671dfe815f89ac9aa7860d2f174ca1d06b17f485bd9a1b9cfed4bf01642d8e92ab37a7199f1977849e808f559b
  aws_account_key: <%= ENV['AWS_ACCOUNT_KEY'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  app_host: <%= ENV["APP_HOST"] %>

test:
  secret_key_base: c2867906b82827aa935dd257554364e7b2d82e3caab067537484919360f7e7f50d49ae1a39cc10bf34cdc2d00b25b7665a357d96c68ec7d583fd9e2c2e8ac001
  aws_account_key: <%= ENV['AWS_ACCOUNT_KEY'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  app_host: <%= ENV["APP_HOST"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_account_key: <%= ENV['AWS_ACCOUNT_KEY'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  app_host: <%= ENV["APP_HOST"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_account_key: <%= ENV['AWS_ACCOUNT_KEY'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  app_host: <%= ENV["APP_HOST"] %>
